POST http://localhost:3030/my-app/users
Content-Type: application/json

{
  "nombre": "Ejemplo Usuario",
  "correo_electronico": "ejemplo@example.com",
  "contrasena": "miContrasenaSegura",
  "fecha_de_creacion": "2023-12-05T12:00:00",
  "usuario_de_creacion": "admin",
  "fecha_de_actualizacion": "2023-12-05T12:30:00",
  "usuario_de_actualizacion": "admin",
  "activo": 1,
  "numero_de_compras": 5,
  "campo_adicional": "Valor adicional"
}

###list users
GET http://localhost:3030/my-app/users


###get 1 user
GET http://localhost:3030/my-app/users/1

###update user
PUT http://localhost:3030/my-app/users/1
Content-Type: application/json

{
  "nombre": "Ejemplo Usuario 1",
  "correo_electronico": "ejemplo@example.com",
  "contrasena": "miContrasenaSegura",
  "fecha_de_creacion": "2023-12-05T12:00:00",
  "usuario_de_creacion": "admin",
  "fecha_de_actualizacion": "2023-12-05T12:30:00",
  "usuario_de_actualizacion": "admin",
  "activo": 1,
  "numero_de_compras": 5,
  "campo_adicional": "Valor adicional"
}

###delete user
DELETE http://localhost:3030/my-app/users/1
